### ISSUE TITLE
类似网站

### ISSUE THREAD

**Issue by linsongze** [kakuiho/wsengine#2]
https://www.jsr9.com/
https://www.tiantianbt.net/
https://www.dy2018.com/
https://www.dytt8.net/index2.htm
https://www.ygdy8.com/index.html
https://yyets.dmesg.app/
https://www.66e.cc/
https://www.yinfans.me/
https://www.chapianyuan.com/
https://www.chaospace.fun/
https://gaoqing.fm/

**Comment by kakuiho** [comment]
## 不收录

1 全是低码率
2 不支持 GET 
3 搜索限制
4 搜任何关键字都是空结果
5 点击搜索结果跳转过去提示，「页面已被删除或不存在」
7 不支持GET；搜索限制
10 强制登陆

## 收录

6 信息清晰
8 片源少但高清
9 信息清晰
